import type * as C from '@clubhouse/contracts';
import type { z } from 'zod';
import { del, get, patch, post, put, url } from './http';

type Ok = { ok: true };
type In<T extends z.ZodType> = z.input<T>;

/** Admin API under /api/admin (role-guarded and behind the 12-hour admin idle window). */
export const adminApi = {
  dashboard: () => get<C.AdminDashboardResponse>('/admin/dashboard'),
  members: {
    list: () => get<C.AdminMemberRow[]>('/admin/members'),
    create: (b: In<typeof C.CreateMemberRequest>) => post<{ member: C.AdminMemberRow; tempPassword: string }>('/admin/members', b),
    get: (id: string) => get<C.AdminMemberDetail>(`/admin/members/${id}`),
    update: (id: string, b: In<typeof C.UpdateMemberRequest>) => patch<C.AdminMemberRow>(`/admin/members/${id}`, b),
    role: (id: string, b: In<typeof C.RoleChangeRequest>) => post<C.AdminMemberRow>(`/admin/members/${id}/role`, b),
    resetPassword: (id: string) => post<{ tempPassword: string }>(`/admin/members/${id}/reset-password`),
    deactivate: (id: string, reason?: string) => post<C.AdminMemberRow>(`/admin/members/${id}/deactivate`, { reason }),
    reactivate: (id: string) => post<C.AdminMemberRow>(`/admin/members/${id}/reactivate`),
    deleteData: (id: string, b: In<typeof C.TypedConfirmRequest>) => post<Ok>(`/admin/members/${id}/delete-data`, b),
    revokeSessions: (id: string) => post<{ revoked: number }>(`/admin/members/${id}/revoke-sessions`),
    resetTotp: (id: string, reason: string) => post<Ok>(`/admin/members/${id}/reset-totp`, { reason }),
    setVacation: (id: string, b: { from: string; to: string }) => post<Ok>(`/admin/members/${id}/vacation`, b),
    import: (b: In<typeof C.ImportMembersRequest>) => post<C.ImportMembersResult>('/admin/members/import', b),
  },
  goals: {
    list: () => get<C.AdminGoalRow[]>('/admin/goals'),
    update: (userId: string, b: In<typeof C.AdminGoalUpdate>) => put<C.AdminGoalRow>(`/admin/goals/${userId}`, b),
    override: (userId: string, b: In<typeof C.OverrideTargetsRequest>) => post<C.AdminGoalRow>(`/admin/goals/${userId}/override`, b),
    clearOverride: (userId: string, reason: string) => post<C.AdminGoalRow>(`/admin/goals/${userId}/clear-override`, { reason }),
    memberSettings: (userId: string, b: In<typeof C.MemberTargetSettingsRequest>) => patch<C.AdminGoalRow>(`/admin/goals/${userId}/settings`, b),
  },
  diets: {
    list: () => get<C.AdminDietListRow[]>('/admin/diets'),
    templates: () => get<C.AdminDietPlan[]>('/admin/diets/templates'),
    plan: (planId: string) => get<C.AdminDietPlan>(`/admin/diets/plans/${planId}`),
    createDraft: (b: In<typeof C.CreateDraftRequest>) => post<C.AdminDietPlan>('/admin/diets/plans', b),
    updatePlan: (planId: string, b: In<typeof C.UpdatePlanRequest>) => patch<C.AdminDietPlan>(`/admin/diets/plans/${planId}`, b),
    deletePlan: (planId: string) => del<Ok>(`/admin/diets/plans/${planId}`),
    addOption: (planId: string, b: In<typeof C.UpsertOptionRequest>) => post<C.AdminDietPlan>(`/admin/diets/plans/${planId}/options`, b),
    updateOption: (planId: string, optionId: string, b: In<typeof C.UpsertOptionRequest>) => put<C.AdminDietPlan>(`/admin/diets/plans/${planId}/options/${optionId}`, b),
    deleteOption: (planId: string, optionId: string) => del<C.AdminDietPlan>(`/admin/diets/plans/${planId}/options/${optionId}`),
    review: (planId: string, slot: C.MealSlot) => post<C.AdminDietPlan>(`/admin/diets/plans/${planId}/review`, { slot }),
    publish: (planId: string, note: string | null) => post<C.AdminDietPlan>(`/admin/diets/plans/${planId}/publish`, { note }),
    saveAsTemplate: (planId: string, name: string) => post<C.AdminDietPlan>(`/admin/diets/plans/${planId}/template`, { name }),
    diff: (planId: string, otherId: string) => get<C.DietDiff>(`/admin/diets/plans/${planId}/diff/${otherId}`),
    draftWithAi: (b: In<typeof C.DraftWithAiRequest>) => post<C.AdminDietPlan>('/admin/diets/ai-draft', b),
    feedback: (userId: string) => get<C.DietFeedbackView>(`/admin/diets/members/${userId}/feedback`),
    bulkAssign: (b: In<typeof C.BulkAssignRequest>) => post<{ created: number }>('/admin/diets/bulk-assign', b),
  },
  foods: {
    list: (q: { q?: string; source?: string; verified?: '0' | '1'; limit?: number }) => get<C.AdminFoodRow[]>('/admin/foods', q),
    update: (id: string, b: In<typeof C.AdminFoodUpdate>) => patch<C.AdminFoodRow>(`/admin/foods/${id}`, b),
    merge: (b: In<typeof C.MergeFoodsRequest>) => post<Ok>('/admin/foods/merge', b),
    promote: (id: string) => post<C.AdminFoodRow>(`/admin/foods/${id}/promote`),
    delete: (id: string) => del<Ok>(`/admin/foods/${id}`),
    import: (csv: string) => post<{ total: number; inserted: number; updated: number; errors: string[] }>('/admin/foods/import', { csv }),
  },
  habits: {
    list: () => get<C.AdminHabitsResponse>('/admin/habits'),
    adherence: () => get<C.AdminHabitAdherence>('/admin/habits/adherence'),
    create: (b: In<typeof C.AdminHabitInput>) => post<C.AdminHabitDto>('/admin/habits', b),
    update: (id: string, b: In<typeof C.AdminHabitInput>) => put<C.AdminHabitDto>(`/admin/habits/${id}`, b),
    setEnabled: (id: string, enabled: boolean) => post<C.AdminHabitDto>(`/admin/habits/${id}/enabled`, { enabled }),
    archive: (id: string) => post<Ok>(`/admin/habits/${id}/archive`),
    addTemplate: (key: string) => post<C.AdminHabitDto>(`/admin/habits/templates/${key}`),
    setOrder: (ids: string[]) => put<C.AdminHabitsResponse>('/admin/habits/order', { ids }),
    syncOrders: (userIds?: string[]) => post<{ synced: number }>('/admin/habits/order/sync', { userIds }),
  },
  plans: {
    list: () => get<C.AdminPlanRow[]>('/admin/plans'),
    get: (userId: string) => get<{ items: C.PlanItemDto[]; note: string | null; weeks: { weekStart: string; done: number; planned: number }[]; usualDays: number[] }>(`/admin/plans/${userId}`),
    upsert: (userId: string, b: In<typeof C.UpsertPlanRequest>) => put<Ok>(`/admin/plans/${userId}`, b),
    assign: (b: In<typeof C.AssignPlanTemplateRequest>) => post<{ updated: number }>('/admin/plans/assign', b),
    ranking: () => get<{ person: C.PersonRef; done: number; planned: number; pct: number }[]>('/admin/plans/ranking'),
    proposals: () => get<{ id: string; person: C.PersonRef; text: string; status: string; adminReply: string | null; createdAt: string }[]>('/admin/plans/proposals'),
    replyProposal: (id: string, b: In<typeof C.ProposalReplyRequest>) => post<Ok>(`/admin/plans/proposals/${id}`, b),
    restWeeks: () => get<{ id: string; person: C.PersonRef; weekStart: string; status: string; reason: string | null }[]>('/admin/plans/rest-weeks'),
    decideRestWeek: (id: string, status: 'approved' | 'declined') => post<Ok>(`/admin/plans/rest-weeks/${id}`, { status }),
    setRestWeek: (b: In<typeof C.AdminRestWeekRequest>) => post<Ok>('/admin/plans/rest-weeks', b),
  },
  chat: {
    list: (q: { q?: string; userId?: string; from?: string; to?: string; reported?: '1'; before?: number; limit?: number }) => get<{ messages: (C.ChatMessageDto & { reports: number; flaggedKeywords: string[] })[]; hasMore: boolean }>('/admin/chat/messages', q),
    pin: (id: string, on: boolean) => post<Ok>(`/admin/chat/messages/${id}/pin`, { on }),
    delete: (id: string) => del<Ok>(`/admin/chat/messages/${id}`),
    announce: (b: In<typeof C.AnnouncementRequest>) => post<C.AnnouncementDto>('/admin/chat/announcements', b),
    announcements: () => get<C.AnnouncementDto[]>('/admin/chat/announcements'),
    clearPreview: (from: string, to: string) => post<{ messages: number; images: number; confirmWord: string }>('/admin/chat/clear/preview', { from, to }),
    clear: (b: In<typeof C.ClearChatRequest>) => post<{ messages: number; images: number }>('/admin/chat/clear', b),
    reports: () => get<{ id: string; message: C.ChatMessageDto; reporter: C.PersonRef; reason: string; status: string; createdAt: string }[]>('/admin/chat/reports'),
    resolveReport: (id: string, b: In<typeof C.ReportResolveRequest>) => post<Ok>(`/admin/chat/reports/${id}`, b),
    mute: (b: In<typeof C.MuteRequest>) => post<Ok>('/admin/chat/mutes', b),
    unmute: (userId: string) => del<Ok>(`/admin/chat/mutes/${userId}`),
    mutes: () => get<{ person: C.PersonRef; until: string; reason: string }[]>('/admin/chat/mutes'),
    keywords: () => get<{ keywords: string[] }>('/admin/chat/keywords'),
    setKeywords: (keywords: string[]) => put<{ keywords: string[] }>('/admin/chat/keywords', { keywords }),
  },
  memes: {
    list: () => get<C.MemeDto[]>('/admin/memes'),
    create: (b: In<typeof C.CreateMemeRequest>) => post<C.MemeDto>('/admin/memes', b),
    update: (id: string, b: In<typeof C.UpdateMemeRequest>) => patch<C.MemeDto>(`/admin/memes/${id}`, b),
    bulk: (b: In<typeof C.BulkMemeRequest>) => post<{ affected: number }>('/admin/memes/bulk', b),
    triggers: () => get<C.AdminTriggerDto[]>('/admin/triggers'),
    createTrigger: (b: In<typeof C.TriggerDefinition>) => post<C.AdminTriggerDto>('/admin/triggers', b),
    updateTrigger: (id: string, b: In<typeof C.TriggerDefinition>) => put<C.AdminTriggerDto>(`/admin/triggers/${id}`, b),
    toggleTrigger: (id: string, enabled: boolean) => post<C.AdminTriggerDto>(`/admin/triggers/${id}/toggle`, { enabled }),
    deleteTrigger: (id: string) => del<Ok>(`/admin/triggers/${id}`),
    dryRun: (triggerId: string | 'all', b: In<typeof C.DryRunRequest>) => post<C.DryRunResult[]>(`/admin/triggers/${triggerId}/dry-run`, b),
    fireTest: (id: string) => post<{ memeId: string | null; memeUrl: string | null; caption: string }>(`/admin/triggers/${id}/fire-test`),
    evaluations: (id: string) => get<{ createdAt: string; person: C.PersonRef | null; event: string; fired: boolean; reasons: string[] }[]>(`/admin/triggers/${id}/evaluations`),
  },
  ai: {
    overview: () => get<C.AdminAiResponse>('/admin/ai'),
    setGlobal: (on: boolean, reason?: string) => post<Ok>('/admin/ai/global', { on, reason }),
    updateFeature: (key: string, b: In<typeof C.AiFeatureUpdate>) => patch<Ok>(`/admin/ai/features/${key}`, b),
    budget: (b: In<typeof C.AiBudgetUpdate>) => put<Ok>('/admin/ai/budget', b),
    addPricing: (b: In<typeof C.AiPricingRow>) => post<Ok>('/admin/ai/pricing', b),
    retention: (b: In<typeof C.AiRetentionUpdate>) => put<Ok>('/admin/ai/retention', b),
    usage: (from: string, to: string) => get<C.AiUsageRow[]>('/admin/ai/usage', { from, to }),
    usageCsvUrl: (from: string, to: string) => url('/admin/ai/usage.csv', { from, to }),
    calls: (q: { userId?: string; feature?: string; outcome?: string; before?: string; limit?: number }) => get<{ calls: C.AiCallRow[]; hasMore: boolean }>('/admin/ai/calls', q),
    call: (id: string) => get<C.AiCallRow>(`/admin/ai/calls/${id}`),
    registry: () => get<{ key: string; name: string; purpose: string; trigger: string; dataSent: string; fallback: string; defaultModel: string; timeoutMs: number; promptVersion: string; sourceFile: string; system: string | null }[]>('/admin/ai/registry'),
    testCall: (key: string) => post<{ ok: boolean; reason: string | null; message: string | null; output: unknown; usage: unknown; callId: string | null }>(`/admin/ai/test/${key}`),
  },
  notifications: {
    defaults: () => get<{ defaults: Record<string, C.NotificationDefault>; defaultQuietHours: { start: string; end: string } | null; copyPool: Record<string, string[]>; labels: Record<string, { label: string; hint: string; group: string; locked: boolean }> }>('/admin/notifications/defaults'),
    updateDefaults: (b: In<typeof C.NotificationDefaultsUpdate>) => put<Ok>('/admin/notifications/defaults', b),
    pushHealth: () => get<C.PushHealthResponse>('/admin/notifications/push-health'),
    testToMe: () => post<{ delivered: number; devices: number }>('/admin/notifications/test'),
  },
  settings: {
    get: () => get<{ name: string; timezone: string; units: 'metric' | 'imperial'; logoUrl: string | null; settings: C.TeamSettings }>('/admin/settings'),
    update: (b: C.TeamSettingsUpdate) => patch<{ name: string; timezone: string; units: 'metric' | 'imperial'; logoUrl: string | null; settings: C.TeamSettings }>('/admin/settings', b),
  },
  retention: {
    get: () => get<C.RetentionResponse>('/admin/retention'),
    update: (b: In<typeof C.RetentionUpdate>) => put<Ok>('/admin/retention', b),
    run: (dryRun: boolean) => post<{ images: number; bytes: number; dryRun: boolean }>('/admin/retention/run', { dryRun }),
    exportTeam: () => post<{ id: string; status: string; url: string | null }>('/admin/exports'),
    handleDeletion: (id: string, action: 'done' | 'dismissed') => post<Ok>(`/admin/deletion-requests/${id}`, { action }),
  },
  audit: {
    list: (q: Partial<Record<'actorId' | 'action' | 'targetType' | 'memberId' | 'from' | 'to' | 'highImpact' | 'cursor' | 'limit', string | number>>) => get<{ rows: C.AuditRow[]; nextCursor: number | null }>('/admin/audit', q),
    csvUrl: (q: Record<string, string>) => url('/admin/audit.csv', q),
  },
  sessions: {
    list: () => get<C.AdminSessionRow[]>('/admin/sessions'),
    revoke: (id: string) => del<Ok>(`/admin/sessions/${id}`),
  },
  jobs: {
    runs: () => get<C.JobRunRow[]>('/admin/jobs/runs'),
    run: (step: string) => post<{ ok: boolean; stats: Record<string, unknown> }>('/admin/jobs/run', { step }),
  },
};
