import type * as C from '@clubhouse/contracts';
import { del, get, patch, post, put, upload, url } from './http';

type Ok = { ok: true };

/** Member-facing API. Every path here is implemented by packages/server (see interface/http/routes). */
export const api = {
  auth: {
    login: (b: C.LoginRequest) => post<C.LoginResponse>('/auth/login', b),
    logout: () => post<Ok>('/auth/logout'),
    logoutAll: () => post<Ok>('/auth/logout-all'),
    changePassword: (b: C.ChangePasswordRequest) => post<Ok>('/auth/change-password', b),
    verifyTotp: (code: string) => post<Ok>('/auth/totp/verify', { code }),
    enrolTotp: () => post<C.TotpEnrolResponse>('/auth/totp/enrol'),
    confirmTotp: (code: string) => post<C.TotpConfirmResponse>('/auth/totp/confirm', { code }),
    disableTotp: (code: string) => post<Ok>('/auth/totp/disable', { code }),
    reauth: (b: C.ReauthRequest) => post<Ok>('/auth/reauth', b),
    sessions: () => get<C.SessionDto[]>('/auth/sessions'),
    revokeSession: (id: string) => del<Ok>(`/auth/sessions/${id}`),
  },
  me: () => get<C.MeResponse & { mfaPending: boolean }>('/me'),
  profile: {
    get: () => get<{ profile: C.ProfileDto; targets: C.TargetsDto | null }>('/profile'),
    onboarding: (b: C.OnboardingRequest) => post<{ targets: C.TargetsDto | null }>('/profile/onboarding', b),
    update: (b: C.ProfileUpdateRequest) => patch<{ profile: C.ProfileDto; targets: C.TargetsDto | null }>('/profile', b),
    previewTargets: (b: Record<string, unknown>) => post<{ preview: (C.TargetsDto & { kcal: number }) | null }>('/profile/targets/preview', b),
    updateGoal: (b: C.GoalUpdateRequest) => put<{ targets: C.TargetsDto | null }>('/profile/goal', b),
    updatePreferences: (b: C.PreferencesUpdateRequest) => patch<{ profile: C.ProfileDto; targets: C.TargetsDto | null }>('/profile/preferences', b),
    setVacation: (b: C.VacationRequest) => post<{ vacationRanges: { from: string; to: string }[] }>('/profile/vacation', b),
    endVacation: () => del<{ vacationRanges: { from: string; to: string }[] }>('/profile/vacation'),
    requestDeletion: (note: string | null) => post<{ id: string; status: string }>('/profile/deletion-request', { note }),
    exportUrl: (format: 'csv' | 'json') => url('/profile/export', { format }),
  },
  foods: {
    search: (q: string, slot?: C.MealSlot, signal?: AbortSignal) => get<C.FoodSearchResponse>('/foods/search', { q, slot }, signal),
    usuals: () => get<C.UsualFood[]>('/foods/usuals'),
    catalog: (q: { since?: string; after?: string; limit?: number }, signal?: AbortSignal) => get<C.FoodCatalogPage>('/foods/catalog', q, signal),
    get: (id: string) => get<C.FoodDetail>(`/foods/${id}`),
    create: (b: C.FoodDraft) => post<C.FoodSearchResult>('/foods', b),
    update: (id: string, b: C.FoodDraft) => put<C.FoodSearchResult>(`/foods/${id}`, b),
    favourite: (id: string, on: boolean) => post<Ok>(`/foods/${id}/favourite`, { on }),
    mine: () => get<{ foods: C.FoodSearchResult[]; recipes: C.RecipeDto[] }>('/foods/mine'),
    deleteMine: (id: string) => del<Ok>(`/foods/${id}`),
  },
  recipes: {
    get: (id: string) => get<C.RecipeDto>(`/recipes/${id}`),
    create: (b: C.RecipeRequest) => post<C.RecipeDto>('/recipes', b),
    update: (id: string, b: C.RecipeRequest) => put<C.RecipeDto>(`/recipes/${id}`, b),
    delete: (id: string) => del<Ok>(`/recipes/${id}`),
  },
  activityTypes: () => get<C.ActivityTypeDto[]>('/activity-types'),
  logs: {
    upsertFood: (id: string, b: C.FoodLogUpsert) => put<C.UpsertResult<C.FoodLogDto>>(`/logs/food/${id}`, b),
    upsertActivity: (id: string, b: C.ActivityLogUpsert) => put<C.UpsertResult<C.ActivityLogDto>>(`/logs/activity/${id}`, b),
    upsertWeight: (id: string, b: C.WeightUpsert) => put<C.UpsertResult<C.WeightEntryDto>>(`/logs/weight/${id}`, b),
    forDate: (date: string) => get<{ foodLogs: C.FoodLogDto[]; activityLogs: C.ActivityLogDto[]; weight: C.WeightEntryDto | null }>('/logs', { date }),
    food: (id: string) => get<C.FoodLogDto>(`/logs/food/${id}`),
    sync: (b: C.SyncRequest) => post<C.SyncResult>('/sync', b),
    changes: (since: string | null) => get<C.ChangesResponse>('/sync/changes', { since }),
  },
  today: (date?: string) => get<C.TodayResponse>('/today', { date }),
  ai: {
    foodPhoto: (form: FormData) => upload<C.RecognitionResponse>('/ai/food-photo', form),
    foodText: (b: { text: string; slot: C.MealSlot }) => post<C.RecognitionResponse>('/ai/food-text', b),
    summary: (date?: string) => get<C.SummaryResponse>('/ai/summary', { date }),
    dismissNotice: () => post<Ok>('/ai/notice-seen'),
  },
  media: {
    upload: (form: FormData) => upload<C.UploadResponse>('/media', form),
  },
  diet: {
    get: (date?: string, dayType?: 'training' | 'rest') => get<C.DietResponse>('/diet', { date, dayType }),
    previous: (planId: string) => get<C.DietResponse>(`/diet/plans/${planId}`),
    logOption: (optionId: string, b: C.LogOptionRequest) => post<C.UpsertResult<C.FoodLogDto>>(`/diet/options/${optionId}/log`, b),
    feedback: (optionId: string, reaction: 'favourite' | 'dislike' | null) => post<Ok>(`/diet/options/${optionId}/feedback`, { reaction }),
  },
  habits: {
    day: (date?: string) => get<C.HabitDayResponse>('/habits', { date }),
    week: () => get<C.HabitWeekResponse>('/habits/week'),
    get: (id: string) => get<C.HabitDetailResponse>(`/habits/${id}`),
    checkin: (id: string, b: C.HabitCheckinUpsert) => put<C.UpsertResult<C.HabitCheckinDto>>(`/habits/checkins/${id}`, b),
    prefs: (id: string, b: C.HabitPrefUpdate) => patch<Ok>(`/habits/${id}/prefs`, b),
    /** `null` goes back to the team order. */
    order: (ids: string[] | null) => put<{ customOrder: boolean }>('/habits/order', { ids }),
  },
  plan: {
    get: () => get<C.MyPlanResponse>('/activity-plan'),
    setDays: (b: C.SetPlanDaysRequest) => put<C.MyPlanResponse>('/activity-plan/days', b),
    propose: (text: string) => post<Ok>('/activity-plan/proposals', { text }),
    restWeek: (weekStart: string, reason?: string) => post<Ok>('/activity-plan/rest-week', { weekStart, reason }),
  },
  progress: {
    weight: (range: C.WeightProgressResponse['range']) => get<C.WeightProgressResponse>('/progress/weight', { range }),
    whatIf: (delta: number) => get<C.ForecastDto>('/progress/what-if', { delta }),
    calories: (range: C.CaloriesProgressResponse['range']) => get<C.CaloriesProgressResponse>('/progress/calories', { range }),
    nutrients: (weekStart?: string) => get<C.NutrientGridResponse>('/progress/nutrients', { weekStart }),
    activity: () => get<C.ActivityProgressResponse>('/progress/activity'),
    consistency: () => get<C.ConsistencyResponse>('/progress/consistency'),
    recaps: () => get<C.RecapDto[]>('/progress/recaps'),
  },
  momentum: () => get<C.MomentumResponse>('/momentum'),
  badgesSeen: () => post<Ok>('/momentum/badges-seen'),
  team: {
    summary: (date?: string) => get<C.TeamSummaryResponse>('/team/summary', { date }),
    memberDay: (memberId: string, date?: string) => get<C.MemberDayResponse>(`/team/members/${memberId}/day`, { date }),
    board: (week?: string) => get<C.BoardResponse>('/team/board', { week }),
    memberPoints: (memberId: string, week?: string) => get<C.MemberPointsResponse>(`/team/members/${memberId}/points`, { week }),
    memberProfile: (memberId: string) => get<C.MemberProfileResponse>(`/team/members/${memberId}/profile`),
  },
  chat: {
    list: (q: { after?: number; before?: number; limit?: number }) => get<C.ChatPageResponse>('/chat/messages', q),
    changes: (q: { since?: string; epoch?: string; limit?: number }, signal?: AbortSignal) => get<C.ChatChangesResponse>('/chat/changes', q, signal),
    send: (id: string, b: C.SendMessageRequest) => put<{ message: C.ChatMessageDto; duplicate: boolean }>(`/chat/messages/${id}`, b),
    delete: (id: string) => del<Ok>(`/chat/messages/${id}`),
    react: (id: string, emoji: string, on: boolean) => post<Ok>(`/chat/messages/${id}/reactions`, { emoji, on }),
    report: (id: string, reason: string) => post<Ok>(`/chat/messages/${id}/report`, { reason }),
    read: (seq: number) => post<Ok>('/chat/read', { seq }),
    presence: () => post<Ok>('/chat/presence'),
    members: () => get<C.ChatMemberDto[]>('/chat/members'),
    memes: () => get<C.MemeDto[]>('/chat/memes'),
    suggestMeme: (imageId: string, caption: string) => post<Ok>('/chat/memes/suggest', { imageId, caption }),
    unread: () => get<{ chat: number; inbox: number }>('/chat/unread'),
  },
  moments: {
    dismiss: (fireId: string) => post<Ok>(`/moments/${fireId}/dismiss`),
    react: (fireId: string) => post<Ok>(`/moments/${fireId}/react`),
    share: (fireId: string) => post<{ message: C.ChatMessageDto }>(`/moments/${fireId}/share`),
  },
  inbox: {
    list: (cursor?: string) => get<C.InboxResponse>('/inbox', { cursor }),
    read: (ids: string[] | 'all') => post<Ok>('/inbox/read', { ids }),
    prefs: () => get<C.NotificationPrefDto[]>('/notifications/preferences'),
    updatePrefs: (b: C.NotificationPrefUpdate) => put<C.NotificationPrefDto[]>('/notifications/preferences', b),
    snooze: (notificationId: string, minutes = 60) => post<Ok>(`/notifications/${notificationId}/snooze`, { minutes }),
    done: (notificationId: string) => post<Ok>(`/notifications/${notificationId}/done`),
  },
  push: {
    subscribe: (b: C.PushSubscribeRequest) => post<{ id: string }>('/push/subscriptions', b),
    unsubscribe: (endpoint: string) => del<Ok>('/push/subscriptions', { endpoint }),
    devices: (endpoint?: string) => get<C.DeviceDto[]>('/push/devices', { endpoint }),
    removeDevice: (id: string) => del<Ok>(`/push/devices/${id}`),
    test: () => post<{ delivered: number; devices: number }>('/push/test'),
  },
};
