/** Query keys for the admin panel. Everything lives under ['admin', …] so a reauth can invalidate it all. */
export const qk = {
  dashboard: ['admin', 'dashboard'] as const,
  members: ['admin', 'members'] as const,
  member: (id: string) => ['admin', 'members', id] as const,
  goals: ['admin', 'goals'] as const,
  diets: ['admin', 'diets'] as const,
  dietTemplates: ['admin', 'diets', 'templates'] as const,
  dietPlan: (id: string) => ['admin', 'diets', 'plan', id] as const,
  dietDiff: (a: string, b: string) => ['admin', 'diets', 'diff', a, b] as const,
  dietFeedback: (userId: string) => ['admin', 'diets', 'feedback', userId] as const,
  foods: (q: Record<string, unknown>) => ['admin', 'foods', q] as const,
  foodsAll: ['admin', 'foods'] as const,
  habits: ['admin', 'habits'] as const,
  habitAdherence: ['admin', 'habits', 'adherence'] as const,
  plans: ['admin', 'plans'] as const,
  plan: (userId: string) => ['admin', 'plans', userId] as const,
  planRanking: ['admin', 'plans', 'ranking'] as const,
  planProposals: ['admin', 'plans', 'proposals'] as const,
  planRestWeeks: ['admin', 'plans', 'rest-weeks'] as const,
  activityTypes: ['activity-types'] as const,
  chatMessages: (q: Record<string, unknown>) => ['admin', 'chat', 'messages', q] as const,
  chatAll: ['admin', 'chat'] as const,
  announcements: ['admin', 'chat', 'announcements'] as const,
  reports: ['admin', 'chat', 'reports'] as const,
  mutes: ['admin', 'chat', 'mutes'] as const,
  keywords: ['admin', 'chat', 'keywords'] as const,
  memes: ['admin', 'memes'] as const,
  triggers: ['admin', 'triggers'] as const,
  triggerEvals: (id: string) => ['admin', 'triggers', id, 'evaluations'] as const,
  ai: ['admin', 'ai'] as const,
  aiUsage: (from: string, to: string) => ['admin', 'ai', 'usage', from, to] as const,
  aiCalls: (q: Record<string, unknown>) => ['admin', 'ai', 'calls', q] as const,
  aiCall: (id: string) => ['admin', 'ai', 'call', id] as const,
  aiRegistry: ['admin', 'ai', 'registry'] as const,
  notifDefaults: ['admin', 'notifications', 'defaults'] as const,
  pushHealth: ['admin', 'notifications', 'push-health'] as const,
  settings: ['admin', 'settings'] as const,
  retention: ['admin', 'retention'] as const,
  audit: (q: Record<string, unknown>) => ['admin', 'audit', q] as const,
  sessions: ['admin', 'sessions'] as const,
  jobs: ['admin', 'jobs'] as const,
};
