/** Query keys. The first segment decides what is persisted offline (infrastructure/queryClient.ts). */
export const qk = {
  me: ['me'] as const,
  today: (date?: string) => ['today', date ?? 'today'] as const,
  diet: (date?: string, dayType?: string) => ['diet', date ?? 'today', dayType ?? 'auto'] as const,
  usuals: ['usuals'] as const,
  foodSearch: (q: string) => ['food-search', q] as const,
  activityTypes: ['activity-types'] as const,
  plan: ['plan'] as const,
  habits: (date?: string) => ['habits', 'day', date ?? 'today'] as const,
  habitWeek: ['habits', 'week'] as const,
  habit: (id: string) => ['habits', 'detail', id] as const,
  momentum: ['momentum'] as const,
  progress: (part: string, arg?: string) => ['progress', part, arg ?? ''] as const,
  team: (date?: string) => ['team', date ?? 'today'] as const,
  memberDay: (id: string, date?: string) => ['team', 'member', id, date ?? 'today'] as const,
  board: (week?: string) => ['team', 'board', week ?? 'current'] as const,
  memberPoints: (id: string, week?: string) => ['team', 'points', id, week ?? 'current'] as const,
  memberProfile: (id: string) => ['team', 'profile', id] as const,
  chat: ['chat'] as const,
  chatMembers: ['chat-members'] as const,
  memes: ['memes'] as const,
  inbox: ['inbox'] as const,
  unread: ['unread'] as const,
  prefs: ['notification-prefs'] as const,
  devices: ['devices'] as const,
  sessions: ['sessions'] as const,
  summary: (date?: string) => ['summary', date ?? 'today'] as const,
  myFoods: ['my-foods'] as const,
  foodLog: (id: string) => ['food-log', id] as const,
  logsForDate: (date: string) => ['logs', date] as const,
  food: (id: string) => ['food', id] as const,
  recipe: (id: string) => ['recipe', id] as const,
};
